export const appRoutes = {
    Empty: '',
    Absences: 'absences',
    App: 'app',
    Chat: 'chat',
    ChatId: 'chatId',
    ConversationInfo: 'info',
    Dashboard: 'dashboard',
    Grades: 'grades',
    Login: 'login',
    LessonId: 'lessonId',
    SchoolInfos: 'schoolInfos',
    Timetable: 'timetable',
    UserSettings: 'userSettings',
}
