export const endpoints = {
    ClassList: 'classlist',
    SchoolInfo: 'schoolinfo',
    Parent: 'parent',
    Login: 'authentication',
    ChangePassword: 'authentication/password',
    Search: 'search',
    User: 'user',
    Chat: 'chat',
    Messages: 'messages',
    Grade: 'grade',
    Timetable: 'timetable',
    TimetableLayout: 'timetable/layout',
    Absence: 'absence',
    Image: 'image',
}